// Code generated by goctl. DO NOT EDIT.
package types

type GoodsAddReq struct {
	GoodsName     string                  `json:"goods_name"`
	GoodsType     int32                   `json:"goods_type"`
	Status        int32                   `json:"status"`
	Description   *string                 `json:"description,optional"`
	Specification []*SpecificationAddList `json:"specification"`
}

type GoodsAddResp struct {
}

type GoodsDelReq struct {
	GoodsId int32 `json:"goods_id"`
}

type GoodsDelResp struct {
}

type GoodsList struct {
	MerchantName string               `json:"merchant_name"`
	GoodsId      int32                `json:"goods_id"`
	GoodsName    string               `json:"goods_name"`
	GoodsTypeId  int32                `json:"goods_type_id"`
	Status       int32                `json:"status"`
	List         []*SpecificationList `json:"list"`
}

type GoodsListReq struct {
	Status      int32   `json:"status,omitempty"`
	GoodsTypeId *int32  `json:"goods_type_id,optional"`
	MerchantId  *int32  `json:"merchant_id,optional"`
	GoodsName   *string `json:"goods_name,optional"`
	GoodsID     *int32  `json:"goods_id,optional"`
	Page        int32   `json:"page"`
	Limit       int32   `json:"limit"`
}

type GoodsListResp struct {
	Count  int32        `json:"count"`
	Limit  int32        `json:"limit"`
	Number int32        `json:"number"`
	Page   int32        `json:"page"`
	List   []*GoodsList `json:"list"`
}

type GoodsTypeList struct {
	GoodsTypeId   int32  `json:"goods_type_id"`
	GoodsTypeName string `json:"goods_type_name"`
}

type GoodsTypeListReq struct {
}

type GoodsTypeListResp struct {
	Count int32            `json:"count"`
	List  []*GoodsTypeList `json:"list"`
}

type GoodsUpDateReq struct {
	GoodsId     int32                `json:"goods_id"`
	GoodsName   *string              `json:"goods_name,optional"`
	GoodsTypeId *int32               `json:"goods_type_id,optional"`
	Status      int32                `json:"status"`
	Description *string              `json:"description,optional`
	List        []*SpecificationList `json:"specification,optional"`
}

type GoodsUpDateResp struct {
}

type SpecificationAddList struct {
	Size      string `json:"size"`
	Inventory int32  `json:"inventory"`
	Score     int32  `json:"score"`
}

type SpecificationList struct {
	SpecificationId  int32  `json:"specification_id"`
	Size             string `json:"size"`
	DisplayInventory int32  `json:"display_inventory"`
	RealInventory    int32  `json:"real_inventory"`
	Score            int32  `json:"score"`
}
