// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package orderserve

import (
	"context"

	"TongChi_shop/rpc/shop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMerchantReq          = shop.AddMerchantReq
	AddMerchantResp         = shop.AddMerchantResp
	DelMerchantReq          = shop.DelMerchantReq
	DelMerchantResp         = shop.DelMerchantResp
	GoodsAddReq             = shop.GoodsAddReq
	GoodsAddResp            = shop.GoodsAddResp
	GoodsDelReq             = shop.GoodsDelReq
	GoodsDelResp            = shop.GoodsDelResp
	GoodsList               = shop.GoodsList
	GoodsListReq            = shop.GoodsListReq
	GoodsListResp           = shop.GoodsListResp
	GoodsTypeList           = shop.GoodsTypeList
	GoodsTypeListReq        = shop.GoodsTypeListReq
	GoodsTypeListResp       = shop.GoodsTypeListResp
	GoodsUpdateReq          = shop.GoodsUpdateReq
	GoodsUpdateResp         = shop.GoodsUpdateResp
	LoadImgReq              = shop.LoadImgReq
	LoadImgResp             = shop.LoadImgResp
	MerchantList            = shop.MerchantList
	MerchantListReq         = shop.MerchantListReq
	MerchantListResp        = shop.MerchantListResp
	OrderList               = shop.OrderList
	OrderListReq            = shop.OrderListReq
	OrderListResp           = shop.OrderListResp
	SendEmailAuthReq        = shop.SendEmailAuthReq
	SendEmailAuthResp       = shop.SendEmailAuthResp
	SpecificationReq        = shop.SpecificationReq
	SpecificationResp       = shop.SpecificationResp
	TaskList                = shop.TaskList
	TaskListReq             = shop.TaskListReq
	TaskListResp            = shop.TaskListResp
	TaskTypeList            = shop.TaskTypeList
	TaskTypeListReq         = shop.TaskTypeListReq
	TaskTypeListResp        = shop.TaskTypeListResp
	UpdateCourierNumberReq  = shop.UpdateCourierNumberReq
	UpdateCourierNumberResp = shop.UpdateCourierNumberResp
	UpdateMerchantReq       = shop.UpdateMerchantReq
	UpdateMerchantResp      = shop.UpdateMerchantResp
	UpdateTaskReq           = shop.UpdateTaskReq
	UpdateTaskResp          = shop.UpdateTaskResp
	UploadImgReq            = shop.UploadImgReq
	UploadImgResp           = shop.UploadImgResp
	UserLoginReq            = shop.UserLoginReq
	UserLoginResp           = shop.UserLoginResp

	OrderServe interface {
		// 获取任务列表
		OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error)
		// 更新任务信息
		UpdateCourierNumber(ctx context.Context, in *UpdateCourierNumberReq, opts ...grpc.CallOption) (*UpdateCourierNumberResp, error)
	}

	defaultOrderServe struct {
		cli zrpc.Client
	}
)

func NewOrderServe(cli zrpc.Client) OrderServe {
	return &defaultOrderServe{
		cli: cli,
	}
}

// 获取任务列表
func (m *defaultOrderServe) OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	client := shop.NewOrderServeClient(m.cli.Conn())
	return client.OrderList(ctx, in, opts...)
}

// 更新任务信息
func (m *defaultOrderServe) UpdateCourierNumber(ctx context.Context, in *UpdateCourierNumberReq, opts ...grpc.CallOption) (*UpdateCourierNumberResp, error) {
	client := shop.NewOrderServeClient(m.cli.Conn())
	return client.UpdateCourierNumber(ctx, in, opts...)
}
