// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	Email string `json:"email"`
	Auth  string `json:"auth"`
}

type UserLoginResp struct {
	Token          string `json:"token"`
	ExpirationTime int64  `json:"expirationTime"`
	RefreshTime    int64  `json:"refreshTime"`
}
