// Code generated by goctl. DO NOT EDIT.
package types

type Img struct {
	Data []byte `json:"img"`
}

type LoadImgReq struct {
	GoodsId int32 `json:"goods_id"`
}

type LoadImgResp struct {
	Imgs []*Img `json:"imgs"`
}

type NewTokenReq struct {
}

type NewTokenResp struct {
	Token          string `json:"token"`
	ExpirationTime int64  `json:"expiration_time"`
	RefreshTime    int64  `json:"refresh_time"`
}

type SendAuthReq struct {
	Email string `json:"email"`
}

type SendAuthResp struct {
	OK bool `json:"ok"`
}

type UploadImgReq struct {
	GoodsId int32 `form:"goods_id"`
}

type UploadImgResp struct {
	URL string `json:"url"`
}
