// Code generated by goctl. DO NOT EDIT.
package types

type LoadImgReq struct {
	URL string `json:"url"`
}

type LoadImgResp struct {
	Img []byte `json:"img"`
}

type NewTokenReq struct {
}

type NewTokenResp struct {
	Token          string `json:"token"`
	ExpirationTime int64  `json:"expirationTime"`
	RefreshTime    int64  `json:"refreshTime"`
}

type SendAuthReq struct {
	Email string `json:"email"`
}

type SendAuthResp struct {
	OK bool `json:"ok"`
}

type UploadImgReq struct {
	Img     []byte `json:"img"`
	GoodsId int32  `json:"goodsId"`
}

type UploadImgResp struct {
	URL string `json:"url"`
}
