// Code generated by goctl. DO NOT EDIT.
package types

type TaskList struct {
	TaskId      int32  `json:"taskId"`
	TaksName    string `json:"taksName"`
	TaskTypeId  int32  `json:"taskTypeId"`
	Status      int32  `json:"status"`
	Description string `json:"description"`
	Score       int32  `json:"score"`
}

type TaskListReq struct {
	Status     *int32  `json:"status,omitempty"`
	TaskTypeId *int32  `json:"taskTypeId,omitempty"`
	TaskName   *string `json:"taskName,omitempty"`
	TaskId     *int32  `json:"taskId,omitempty"`
	Page       int32   `json:"page"`
	Limit      int32   `json:"limit"`
}

type TaskListResp struct {
	Count  int32       `json:"count"`
	Limit  int32       `json:"limit"`
	Number int32       `json:"number"`
	Page   int32       `json:"page"`
	List   []*TaskList `json:"list"`
}

type TaskTypeList struct {
	TaskTypeId   int32  `json:"taskTypeId"`
	TaskTypeName string `json:"taskTypeName"`
}

type TaskTypeListReq struct {
}

type TaskTypeListResp struct {
	Count int32           `json:"count"`
	List  []*TaskTypeList `json:"list"`
}

type UpDateTaskReq struct {
	TaskId int32 `json:"taskId"`
	Score  int32 `json:"score"`
}

type UpDateTaskResp struct {
}
