// Code generated by goctl. DO NOT EDIT.
package types

type TaskList struct {
	TaskId      int32  `json:"task_id"`      // 任务ID
	TaskName    string `json:"task_name"`    // 任务名称
	TaskTypeId  int32  `json:"task_type_id"` // 任务类型ID
	Status      int32  `json:"status"`       // 任务状态
	Description string `json:"description"`  // 任务描述
	Score       int32  `json:"score"`        // 任务分数
}

type TaskListReq struct {
	Status     *int32  `json:"status,optional"`       // 任务状态
	TaskTypeId *int32  `json:"task_type_id,optional"` // 任务类型
	TaskName   *string `json:"task_name,optional"`    // 任务名称
	TaskId     *int32  `json:"task_id,optional"`      // 任务ID
	Page       int32   `json:"page"`                  // 页码
	Limit      int32   `json:"limit"`                 // 条数
}

type TaskListResp struct {
	Count  int32       `json:"count"`  // 数据总条数
	Limit  int32       `json:"limit"`  // 条数
	Number int32       `json:"number"` // 总页数
	Page   int32       `json:"page"`   // 当前页码
	List   []*TaskList `json:"list"`   // 任务数据列表
}

type TaskTypeList struct {
	TaskTypeId   int32  `json:"task_type_id"`   // 任务类型ID
	TaskTypeName string `json:"task_type_name"` // 任务类型名称
}

type TaskTypeListReq struct {
}

type TaskTypeListResp struct {
	Count int32           `json:"count"`
	List  []*TaskTypeList `json:"list"`
}

type UpDateTaskReq struct {
	TaskId int32 `json:"task_id"`
	Score  int32 `json:"score"`
}

type UpDateTaskResp struct {
}
