// Code generated by goctl. DO NOT EDIT.
package types

type MerchantAddReq struct {
	MerchantName   string `json:"merchant_name"`   // 商铺名称
	MerchantStatus int32  `json:"merchant_status"` // 商铺状态
	Linkname       string `json:"linkname"`        // 联系人
	Phone          string `json:"phone"`           // 联系方式
}

type MerchantAddResp struct {
}

type MerchantDelReq struct {
	MerchantId int32 `json:"merchant_id"`
}

type MerchantDelResp struct {
}

type MerchantList struct {
	MerchantName   string `json:"merchant_name"`   // 商铺名称
	MerchantId     int32  `json:"merchant_id"`     // 商铺Id
	MerchantStatus int32  `json:"merchant_status"` // 商铺状态
	Linkname       string `json:"linkname"`        // 联系人
	Role           int32  `json:"role"`            // 角色
}

type MerchantListReq struct {
	MerchantStatus *int32  `json:"merchant_status,optional"` // 商铺状态
	MerchantName   *string `json:"merchant_name,optional"`   // 商铺名称
	MerchantId     *int32  `json:"merchant_id,optional"`     // 商铺ID
	Page           int32   `json:"page"`                     // 页码
	Limit          int32   `json:"limit"`                    // 条数
}

type MerchantListResp struct {
	Count  int32           `json:"count"`
	Limit  int32           `json:"limit"`
	Number int32           `json:"number"`
	Page   int32           `json:"page"`
	List   []*MerchantList `json:"list"`
}

type MerchantUpDateReq struct {
	MerchantId     int32  `json:"merchant_id"`     // 商铺Id
	MerchantName   string `json:"merchant_name"`   // 商铺名称
	MerchantStatus int32  `json:"merchant_status"` // 商铺状态
	Linkname       string `json:"linkname"`        // 联系人
	Phone          string `json:"phone"`           // 联系方式
}

type MerchantUpDateResp struct {
}
