// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package userserve

import (
	"context"

	"TongChi_shop/rpc/shop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMerchantReq          = shop.AddMerchantReq
	AddMerchantResp         = shop.AddMerchantResp
	DelMerchantReq          = shop.DelMerchantReq
	DelMerchantResp         = shop.DelMerchantResp
	GoodsAddReq             = shop.GoodsAddReq
	GoodsAddResp            = shop.GoodsAddResp
	GoodsDelReq             = shop.GoodsDelReq
	GoodsDelResp            = shop.GoodsDelResp
	GoodsList               = shop.GoodsList
	GoodsListReq            = shop.GoodsListReq
	GoodsListResp           = shop.GoodsListResp
	GoodsTypeList           = shop.GoodsTypeList
	GoodsTypeListReq        = shop.GoodsTypeListReq
	GoodsTypeListResp       = shop.GoodsTypeListResp
	GoodsUpdateReq          = shop.GoodsUpdateReq
	GoodsUpdateResp         = shop.GoodsUpdateResp
	LoadImgReq              = shop.LoadImgReq
	LoadImgResp             = shop.LoadImgResp
	MerchantList            = shop.MerchantList
	MerchantListReq         = shop.MerchantListReq
	MerchantListResp        = shop.MerchantListResp
	OrderList               = shop.OrderList
	OrderListReq            = shop.OrderListReq
	OrderListResp           = shop.OrderListResp
	SendEmailAuthReq        = shop.SendEmailAuthReq
	SendEmailAuthResp       = shop.SendEmailAuthResp
	SpecificationReq        = shop.SpecificationReq
	SpecificationResp       = shop.SpecificationResp
	TaskList                = shop.TaskList
	TaskListReq             = shop.TaskListReq
	TaskListResp            = shop.TaskListResp
	TaskTypeList            = shop.TaskTypeList
	TaskTypeListReq         = shop.TaskTypeListReq
	TaskTypeListResp        = shop.TaskTypeListResp
	UpdateCourierNumberReq  = shop.UpdateCourierNumberReq
	UpdateCourierNumberResp = shop.UpdateCourierNumberResp
	UpdateMerchantReq       = shop.UpdateMerchantReq
	UpdateMerchantResp      = shop.UpdateMerchantResp
	UpdateTaskReq           = shop.UpdateTaskReq
	UpdateTaskResp          = shop.UpdateTaskResp
	UploadImgReq            = shop.UploadImgReq
	UploadImgResp           = shop.UploadImgResp
	UserLoginReq            = shop.UserLoginReq
	UserLoginResp           = shop.UserLoginResp

	UserServe interface {
		UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error)
	}

	defaultUserServe struct {
		cli zrpc.Client
	}
)

func NewUserServe(cli zrpc.Client) UserServe {
	return &defaultUserServe{
		cli: cli,
	}
}

func (m *defaultUserServe) UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error) {
	client := shop.NewUserServeClient(m.cli.Conn())
	return client.UserLogin(ctx, in, opts...)
}
