// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package functionserve

import (
	"context"

	"TongChi_shop/rpc/shop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GoodsAddReq       = shop.GoodsAddReq
	GoodsAddResp      = shop.GoodsAddResp
	GoodsDelReq       = shop.GoodsDelReq
	GoodsDelResp      = shop.GoodsDelResp
	GoodsList         = shop.GoodsList
	GoodsListReq      = shop.GoodsListReq
	GoodsListResp     = shop.GoodsListResp
	GoodsUpdateReq    = shop.GoodsUpdateReq
	GoodsUpdateResp   = shop.GoodsUpdateResp
	SendEmailAuthReq  = shop.SendEmailAuthReq
	SendEmailAuthResp = shop.SendEmailAuthResp
	SpecificationReq  = shop.SpecificationReq
	SpecificationResp = shop.SpecificationResp
	TaskReq           = shop.TaskReq
	UserLoginReq      = shop.UserLoginReq
	UserLoginResp     = shop.UserLoginResp

	FunctionServe interface {
		SendEmailAuth(ctx context.Context, in *SendEmailAuthReq, opts ...grpc.CallOption) (*SendEmailAuthResp, error)
	}

	defaultFunctionServe struct {
		cli zrpc.Client
	}
)

func NewFunctionServe(cli zrpc.Client) FunctionServe {
	return &defaultFunctionServe{
		cli: cli,
	}
}

func (m *defaultFunctionServe) SendEmailAuth(ctx context.Context, in *SendEmailAuthReq, opts ...grpc.CallOption) (*SendEmailAuthResp, error) {
	client := shop.NewFunctionServeClient(m.cli.Conn())
	return client.SendEmailAuth(ctx, in, opts...)
}
