// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package server

import (
	"context"

	"TongChi_shop/rpc/internal/logic/orderserve"
	"TongChi_shop/rpc/internal/svc"
	"TongChi_shop/rpc/shop"
)

type OrderServeServer struct {
	svcCtx *svc.ServiceContext
	shop.UnimplementedOrderServeServer
}

func NewOrderServeServer(svcCtx *svc.ServiceContext) *OrderServeServer {
	return &OrderServeServer{
		svcCtx: svcCtx,
	}
}

// 获取任务列表
func (s *OrderServeServer) OrderList(ctx context.Context, in *shop.OrderListReq) (*shop.OrderListResp, error) {
	l := orderservelogic.NewOrderListLogic(ctx, s.svcCtx)
	return l.OrderList(in)
}

// 更新任务信息
func (s *OrderServeServer) UpdateCourierNumber(ctx context.Context, in *shop.UpdateCourierNumberReq) (*shop.UpdateCourierNumberResp, error) {
	l := orderservelogic.NewUpdateCourierNumberLogic(ctx, s.svcCtx)
	return l.UpdateCourierNumber(in)
}
