// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	function "TongChi_shop/api/function_api/internal/handler/function"
	"TongChi_shop/api/function_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthentication},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/loadImg",
					Handler: LoadimgHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/newToken",
					Handler: NewTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uploadImg",
					Handler: UploadImgHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/function"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sendAuth",
				Handler: function.SendAuthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/function"),
	)
}
