// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TongChi_shop/api/merchant_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/MerchantAdd",
				Handler: MerchantAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/MerchantUpdate",
				Handler: MerchantUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/merchantDel",
				Handler: MerchantDelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/merchantList",
				Handler: MerchantListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/merchat"),
	)
}
