// Code generated by goctl. DO NOT EDIT.
package types

type OrderList struct {
	CreateTime        int64   `json:"createTime"`
	OrderId           int32   `json:"orderId"`
	GoodsName         string  `json:"goodsName"`
	SpecificationSize string  `json:"specificationSize"`
	OrderNum          int32   `json:"orderNum"`
	RecipientName     string  `json:"recipientName"`
	Phone             string  `json:"phone"`
	Address           string  `json:"address"`
	Score             int32   `json:"score"`
	CourierNumber     *string `json:"courierNumber,omitempty"`
}

type OrderListReq struct {
	RecipientName  *string `json:"recipientName,omitempty"`
	RecipientPhone *string `json:"recipientPhone,omitempty"`
	OrderTime      *int64  `json:"orderTime,omitempty"`
	GoodsName      *string `json:"goodsName,omitempty"`
	OrderId        *int32  `json:"orderId,omitempty"`
	Page           int32   `json:"page"`
	Limit          int32   `json:"limit"`
}

type OrderListResp struct {
	Count  int32        `json:"count"`
	Limit  int32        `json:"limit"`
	Number int32        `json:"number"`
	Page   int32        `json:"page"`
	List   []*OrderList `json:"list"`
}

type UpdateCourierNumberReq struct {
	OrderId       int32  `json:"orderId"`
	CourierNumber string `json:"courierNumber"`
}

type UpdateCourierNumberResp struct {
}
