// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package server

import (
	"context"

	"TongChi_shop/rpc/internal/logic/merchantserve"
	"TongChi_shop/rpc/internal/svc"
	"TongChi_shop/rpc/shop"
)

type MerchantServeServer struct {
	svcCtx *svc.ServiceContext
	shop.UnimplementedMerchantServeServer
}

func NewMerchantServeServer(svcCtx *svc.ServiceContext) *MerchantServeServer {
	return &MerchantServeServer{
		svcCtx: svcCtx,
	}
}

func (s *MerchantServeServer) MerchantList(ctx context.Context, in *shop.MerchantListReq) (*shop.MerchantListResp, error) {
	l := merchantservelogic.NewMerchantListLogic(ctx, s.svcCtx)
	return l.MerchantList(in)
}

func (s *MerchantServeServer) UpdateMerchant(ctx context.Context, in *shop.UpdateMerchantReq) (*shop.UpdateMerchantResp, error) {
	l := merchantservelogic.NewUpdateMerchantLogic(ctx, s.svcCtx)
	return l.UpdateMerchant(in)
}

func (s *MerchantServeServer) DelMerchant(ctx context.Context, in *shop.DelMerchantReq) (*shop.DelMerchantResp, error) {
	l := merchantservelogic.NewDelMerchantLogic(ctx, s.svcCtx)
	return l.DelMerchant(in)
}
