// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package server

import (
	"context"

	"TongChi_shop/rpc/internal/logic/taskserve"
	"TongChi_shop/rpc/internal/svc"
	"TongChi_shop/rpc/shop"
)

type TaskServeServer struct {
	svcCtx *svc.ServiceContext
	shop.UnimplementedTaskServeServer
}

func NewTaskServeServer(svcCtx *svc.ServiceContext) *TaskServeServer {
	return &TaskServeServer{
		svcCtx: svcCtx,
	}
}

// 获取任务列表
func (s *TaskServeServer) TaskList(ctx context.Context, in *shop.TaskListReq) (*shop.TaskListResp, error) {
	l := taskservelogic.NewTaskListLogic(ctx, s.svcCtx)
	return l.TaskList(in)
}

// 更新任务信息
func (s *TaskServeServer) UpdateTask(ctx context.Context, in *shop.UpdateTaskReq) (*shop.UpdateTaskResp, error) {
	l := taskservelogic.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}
